# Generated by Django 3.2.13 on 2023-01-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos_gramatica_ingles_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('availability', models.BooleanField(default=True, verbose_name='Disponibilidade')),
                ('plus', models.CharField(max_length=100, verbose_name='Questão')),
                ('minus', models.CharField(max_length=100, verbose_name='Questão')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
