# Generated by Django 3.2.13 on 2023-01-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos_gramatica_ingles_app', '0002_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Pontuação', 'verbose_name_plural': 'Pontuações'},
        ),
        migrations.AlterField(
            model_name='score',
            name='minus',
            field=models.CharField(max_length=100, verbose_name='Pontuação negativa'),
        ),
        migrations.AlterField(
            model_name='score',
            name='plus',
            field=models.CharField(max_length=100, verbose_name='Pontuação positiva'),
        ),
    ]
