# Generated by Django 3.2.13 on 2023-01-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos_gramatica_ingles_app', '0004_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=100, verbose_name='Resposta'),
        ),
    ]
