# Generated by Django 3.2.13 on 2023-01-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos_gramatica_ingles_app', '0005_alter_answer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('availability', models.BooleanField(default=True, verbose_name='Disponibilidade')),
                ('question', models.CharField(max_length=100, verbose_name='Questão')),
                ('nouns', models.CharField(max_length=100, verbose_name='Lista de substantivos')),
                ('answer_number', models.CharField(max_length=100, verbose_name='Resposta da alternativa')),
            ],
            options={
                'verbose_name': 'Dado do algoritmo',
                'verbose_name_plural': 'Dados do algoritmo',
            },
        ),
    ]
