# Generated by Django 3.2.13 on 2023-01-09 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogos_gramatica_ingles_app', '0006_algorithm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Algorithm',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
